version: "3.4"
services:
  redis:
    image: redis:6.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
