version: "3.4"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
  scrape:
    build: .
    links:
      - db
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3000"
